# Agent
:author: lencelg from Arcadia Bay
:toc:

## Rational Agent

agent has great impact to our daily life

rational agent::
* Rational: maximally achieving **pre-defined goals**
* Goals are expressed in terms of the **utility** of outcomes
* World is uncertain, so we'll use **expected** utility
* Being rational means acting to **maximize your expected utility**

## Environemnt
an agent exist in the task environment

To define the task environment we use the PEAS (**Performance Measure**, **Environment**, **Actuators**, **Sensors**) description. 

=== types of environment
* **partially observable environments**, the agent does not have full information about the state and
thus the agent must have an internal estimate of the state of the world. This is in contrast to **fully
observable environments**, where the agent has full information about their state.
* **Stochastic environments** have _uncertainty_ in the transition model, i.e. taking an action in a specific
state may have multiple possible outcomes with different probabilities. This is in contrast to **deter-
ministic environments**, where taking an action in a state has a single outcome that is guaranteed to
happen.
* **multi-agent environments** the agent acts in the environments along with other agents. For this reason the agent might need to randomize its actions in order to avoid being **predictable** by other
agents.
* If the environment does not change as the agent acts on it, then this environment is called **static**. This
is contrast to dynamic environments that change as the agent interacts with it.
* If an environment has **known physics**, then the transition model (even if stochastic) is known to the
agent and it can use that when planning a path. If the physics are unknown the agent will need to take
actions deliberately to learn the **unknown dynamics**.